import { MenuItem, GalleryItem, Review, DaySchedule, DailySpecial } from './types';

// Image paths from our generated assets
export const IMAGES = {
  interior: '/uploads/Sala_Interna.jpg',
  tagliere: '/uploads/Tagliere_Umbro.jpg',
  rocciata: '/uploads/Piatto_Rocciata.jpg',
};

export const RESTAURANT_INFO = {
  name: 'Trattoria del Corso',
  address: 'Corso Camillo Benso Conte di Cavour, 54, 06034 Foligno PG, Italia',
  city: 'Foligno',
  province: 'PG',
  postalCode: '06034',
  phone: '+39 3807950582',
  phoneFormatted: '380 795 0582',
  averagePrice: '20 - 30 € a persona',
  googleMapsLink: 'https://maps.google.com/?q=Trattoria+del+Corso+Foligno+Corso+Cavour+54',
  whatsappLink: 'https://wa.me/393807950582',
  coordinates: {
    lat: 42.9546,
    lng: 12.7032
  },
  description: 'Nel cuore del centro storico di Foligno, la Trattoria del Corso celebra l’autenticità della cucina umbra. Ogni piatto è un viaggio nei sapori di una volta, con cottura lenta nel tradizionale forno a legna o pasta fresca trafilata al bronzo e bollita a regola d’arte.',
  features: {
    cookingType: 'Cottura nel Forno a Legna',
    cookingDetail: 'Nel nostro ristorante la brace è regina. Prepariamo tutti i secondi piatti, i contorni saporiti e le specialità in terracotta (i famosi "cocci") direttamente all’interno del forno a legna per un aroma affumicato inimitabile. Per la pasta fresca, utilizziamo un bollitore ad alta precisione che assicura la cottura al dente ideale per esaltare i nostri ricchi sughi.',
    wineSelection: 'Vini dell’Umbria e della Toscana',
    wineDetail: 'La nostra cantina seleziona con passione solo vini provenienti dalle colline umbre e toscane: dal nobile Sagrantino di Montefalco al fruttato Grechetto, fino ai corposi rossi del Chianti e di Montalcino, perfetti da abbinare alle nostre carni cotte a legna.'
  }
};

export const OPENING_HOURS: DaySchedule[] = [
  {
    dayName: 'Lunedì',
    dayCode: 1,
    isClosed: false,
    dinner: { open: '19:30', close: '22:30' }
  },
  {
    dayName: 'Martedì',
    dayCode: 2,
    isClosed: false,
    lunch: { open: '12:30', close: '15:00' },
    dinner: { open: '19:30', close: '22:30' }
  },
  {
    dayName: 'Mercoledì',
    dayCode: 3,
    isClosed: false,
    lunch: { open: '12:30', close: '15:00' },
    dinner: { open: '19:30', close: '22:30' }
  },
  {
    dayName: 'Giovedì',
    dayCode: 4,
    isClosed: false,
    lunch: { open: '12:30', close: '15:30' },
    dinner: { open: '19:30', close: '22:30' }
  },
  {
    dayName: 'Venerdì',
    dayCode: 5,
    isClosed: false,
    dinner: { open: '19:30', close: '22:30' }
  },
  {
    dayName: 'Sabato',
    dayCode: 6,
    isClosed: false,
    lunch: { open: '12:30', close: '15:00' },
    dinner: { open: '19:30', close: '22:30' }
  },
  {
    dayName: 'Domenica',
    dayCode: 0,
    isClosed: false,
    lunch: { open: '12:30', close: '15:00' },
    dinner: { open: '19:30', close: '22:30' }
  }
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "anti-1",
    name: "Tagliere di formaggi misti con miele e marmellate (Quantità: 1 Persona) ",
    description: "Selezione di formaggi tipici umbri tagliati a mano, pecorini locali di grotta affinati, miele, marmellate e con soli 4€ in più si potrà assaggiare un piccolo calice del nostro sagrantino passito D.O.C.G locale",
    price: 12,
    category: "antipasti",
    isWoodFired: false,
    isLocalSpecialty: true,
    allergens: ["glutine", "latte", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "anti-2",
    name: "I \"5 Cocci\" ",
    description: "La nostra specialità imperdibile: quattro ciotole di terracotta con il quinto coccio che sarà in un altro piatto, tutto quanto cotto nel forno a legna. Includono: insalatina di ceci, fonduta di formaggi alpini con miele sopra, insalatina di ricotta con erbe e verdure stagionali, guanciale croccante con glassa sopra e per ultimo delle patate al cartoccio condite con olio e sale, presentate in un piattino differente dai quattro coccetti.",
    price: 22,
    category: "antipasti",
    isWoodFired: true,
    isLocalSpecialty: true,
    isDailySpecial: true,
    allergens: ["sedano", "solfiti", "glutine"],
    isVegetarian: false,
  },
  {
    id: "anti-3",
    name: "Bruschette Miste (Quantità 5)",
    description: "Altro piatto tipico della nostra Umbria, ecco le bruschette miste cotte nel forno, nelle bruschette si potrà assaggiare il classico sale e olio, pomodirini, salciccia spalmata sopra il pane, fonduta di formaggi Alpini con miele sopra e per ultimo un ottimo guanciale croccante con glassa.",
    price: 10,
    category: "antipasti",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "menu-1786542813606-bi3e",
    name: "Acciughe del mar cantarbico con ricotta e pane tostato",
    description: "acciughe del mar Cantarbico accompagnate con ricotta e pane tostato",
    price: 14,
    category: "antipasti",
    isWoodFired: false,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786542667305-oy1l",
    name: "Caprese con mozzarella di bufala e pomodori",
    description: "Caprese estiva con mozzarella di bufala e pomodori stagionali ",
    price: 10,
    category: "antipasti",
    isWoodFired: false,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786541513366-c3sk",
    name: "Delizia contadina patate di Colfiorito, sedano, carota e cipolla rossa di Tropea",
    description: "Delizia contadina composta da verdure stagionali e della nostra zona come le patate di Colfiorito, sedano e carota e la cipolla rossa di Tropea",
    price: 10,
    category: "antipasti",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786541370037-0izn",
    name: "Fonduta di formaggi alpini al coccio con tartufo nero ",
    description: "Fonduta di formaggi alpini al coccio con tartufo nero di Norcia",
    price: 15,
    category: "antipasti",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786541270585-os63",
    name: "Patate al cartoccio con crema di robiola e tartufo nero",
    description: "Le patate al cartoccio sono un piatto tipico umbro e sono composte cosi, una patata intera divisa a metà cotta nel forno a legna, condita successivamente con crema di robiola e tartufo nero di Norcia",
    price: 14,
    category: "antipasti",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786541138688-6ksg",
    name: "Frittatina al forno alle verdure stagionali",
    description: "Frittata alle verdure, cotta nel forno, verudre esclusivamente stagionali",
    price: 10,
    category: "antipasti",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786541079296-ho4a",
    name: "Frittatina al forno al tartufo ",
    description: "Frittata al tartufo, cotta nel forno, tartufo proveniente da Norcia",
    price: 14,
    category: "antipasti",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786539978803-pq8i",
    name: "Tagliere di formaggi misti con miele e marmellate e Salumi di Norcia (Quantità: 2 Persone)",
    description: "Selezione di formaggi tipici umbri tagliati a mano, pecorini locali di grotta affinati, miele, marmellate, selezione di salumi tipici di Norcia e con soli 4€ in più si potrà assaggiare un piccolo calice del nostro sagrantino passito D.O.C.G locale",
    price: 24,
    category: "antipasti",
    isWoodFired: false,
    isLocalSpecialty: true,
    allergens: ["glutine", "latte"],
    isVegetarian: false,
  },
  {
    id: "menu-1786539899934-35ma",
    name: "Tagliere di formaggi misti con miele e marmellate e salumi di Norcia (Quantità: 1 Persona)",
    description: "Selezione di formaggi tipici umbri tagliati a mano, pecorini locali di grotta affinati, miele, marmellate, selezione di salumi tipici di Norcia e con soli 4€ in più si potrà assaggiare un piccolo calice del nostro sagrantino passito D.O.C.G locale",
    price: 12,
    category: "antipasti",
    isWoodFired: false,
    isLocalSpecialty: true,
    allergens: ["glutine", "latte"],
    isVegetarian: false,
  },
  {
    id: "menu-1786539634536-tvyu",
    name: "Tagliere di formaggi misti con miele e marmellate (Quantità: 2 Persone) ",
    description: "Selezione di formaggi tipici umbri tagliati a mano, pecorini locali di grotta affinati, miele, marmellate e con soli 4€ in più si potrà assaggiare un piccolo calice del nostro sagrantino passito D.O.C.G locale",
    price: 24,
    category: "antipasti",
    isWoodFired: false,
    isLocalSpecialty: true,
    allergens: ["glutine", "latte"],
    isVegetarian: true,
  },
  {
    id: "primi-1",
    name: "Gnocchi al Sagrantino",
    description: "Morbidi gnocchi di patate, mantecati con una riduzione vellutata di vino Montefalco Sagrantino D.O.C.G.",
    price: 12,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    isDailySpecial: true,
    allergens: ["glutine", "latte", "uova", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "primi-2",
    name: "Tonnarelli alla Norcina ",
    description: "La regina dei primi piatti umbri. Pasta fresca di grano antico cotta nel nostro bollitore, condita con salsiccia di Norcia sbriciolata, panna fresca d’alpeggio.",
    price: 12,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "latte", "solfiti"],
    isVegetarian: false,
  },
  {
    id: "primi-4",
    name: "Tonnarelli al Ragù di cinghiale",
    description: "Tonnarelli, cotti alla perfezione e condite con ragù di cinghiale selvatico.",
    price: 16,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "uova", "sedano", "solfiti"],
    isVegetarian: false,
  },
  {
    id: "menu-1786545507214-h486",
    name: "Tonnarelli alla Amatriciana",
    description: "Tonnarelli alla Amatriciana, con pepe sopra",
    price: 12,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: false,
  },
  {
    id: "menu-1786545458349-1yge",
    name: "Ravioli cacio e pepe",
    description: "Ravioli cacio e pepe con pecorino sopra",
    price: 14,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: false,
  },
  {
    id: "menu-1786545393521-3y80",
    name: "Cannelloni al ragù di cinghiale",
    description: "Cannelloni al ragù di cinghiale, con pasta frescha e cinghiale fresco",
    price: 16,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: false,
  },
  {
    id: "menu-1786545273313-vo3q",
    name: "Ravioloni fatti a mano ripieni di zucca con crema di parmigiano e tartufo ",
    description: "Ravioloni fatti a mano ripieni di zucca con crema di parmigiano e tartufo nero di Norcia",
    price: 18,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786545176736-2l6x",
    name: "Ravioloni fatti a mano ripieni di ricotta e spinaci ai funghi porcini e tartufo ",
    description: "Ravioloni fatti a mano ripieni di ricotta e spinaci ai funghi porcini della zona e tartufo nero di Norcia",
    price: 18,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786544967254-w8lf",
    name: "Zuppa di legumi ",
    description: "Zuppa di legumi stagionali",
    price: 10,
    category: "primi",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: false,
  },
  {
    id: "menu-1786544911747-53ae",
    name: "Lasagne ai funghi porcini e tartufo",
    description: "Lasagne ai funghi porcini della zona e tartufo nero di Norcia",
    price: 16,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786544845604-u6kl",
    name: "Gnocchi 4 formaggi",
    description: "Gnocchi ai 4 formaggi, con pezzetti di noci sopra",
    price: 12,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786544694835-3vja",
    name: "Tonnarelli alla carbonara ",
    description: "Tonnarelli alla carbonara, con uova, guanciale, pecorino e pepe",
    price: 12,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: false,
  },
  {
    id: "menu-1786544591845-hebi",
    name: "Tonnarelli alla sorrentina",
    description: "Tonnarelli alla sorrentina, con mozzarella stagionale",
    price: 10,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "menu-1786544535978-2ugn",
    name: "Strangozzi burro e tartufo",
    description: "Strangozzi al burro con tartufo nero",
    price: 17,
    category: "primi",
    isWoodFired: true,
    isPastaBoiler: true,
    isLocalSpecialty: true,
    allergens: ["glutine"],
    isVegetarian: true,
  },
  {
    id: "secondi-1",
    name: "Fiorentina al Brace (al kg)",
    description: "Bistecca T-bone di manzo umbro, cotta sul fuoco a legna con brace viva, condita con olio extravergine d'oliva, sale e pepe. Spessore consigliato 3-4cm per un cuore rosa e crosticina croccante.",
    price: 60,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: false,
    allergens: ["solfiti"],
  },
  {
    id: "secondi-2",
    name: "Tagliata di Vitello",
    description: "Fetta di filetto di vitello scottata alla brace nel forno a legna, servita su letto di rucola e Parmigiano Reggiano con scorza di limone e olio extravergine d'oliva.",
    price: 20,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: false,
    allergens: ["solfiti", "latte"],
  },
  {
    id: "secondi-3",
    name: "Filetto alla Griglia",
    description: "Filetto di manzo alla griglia, mantecato con burro di malga, rosmarino fresco e una spolverata di pepe nero macinato al momento.",
    price: 22,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: false,
    allergens: ["solfiti", "latte"],
  },
  {
    id: "secondi-4",
    name: "Filetto al Sagrantino",
    description: "Filetto di manzo selvatico avvolto nella nostra riduzione di vino Montefalco Sagrantino D.O.C.G., con polenta croccante e funghi porcini.",
    price: 23,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti", "glutine"],
  },
  {
    id: "secondi-5",
    name: "Bistecca di Vitello",
    description: "Bistecca di manzo di razza bicellare, grande e spessa, cotta alla brace nel forno a legna con una crosta dorata e una polpa tenera.",
    price: 19,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: false,
    allergens: ["solfiti"],
  },
  {
    id: "secondi-6",
    name: "Grigliata Mista di Maiale",
    description: "Salsicce di Norcia, costine di maiale e spiedini misti, tutti marinati alle erbe aromatiche e arrostiti sulla brace nel forno a legna.",
    price: 14,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "secondi-7",
    name: "La Porcaccia di Maiale",
    description: "Spezzatino di coscetto di maiale cotto lentamente a fuoco lento nel forno a legna con patate novelle, rosmarino e un bicchiere di vino locale.",
    price: 14,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "secondi-8",
    name: "Stinco di Maiale al Forno con Patate",
    description: "Stinco di maiale intero cotto al forno con patate novelle arrosto, aglio, rosmarino e una crosta dorata realizzata nel nostro forno a legna.",
    price: 16,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: false,
    allergens: ["solfiti", "sedano"],
  },
  {
    id: "secondi-9",
    name: "Pollo al Coccio",
    description: "Cosce di pollo biologico nostrano, marinate con erbe aromatiche e spezie, cotte a fuoco lento per ore nel forno a legna dentro un coccio di terracotta con olive nere, pomodorini e vino bianco.",
    price: 13,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti", "sedano"],
  },
  {
    id: "secondi-10",
    name: "Cotoletta di Petto di Pollo",
    description: "Fettine di petto di pollo batterate al parmigiano e pangrattato, scottate in padella fino a doratura croccante, servite con una spolverata di pepe e un filo di olio extravergine.",
    price: 12,
    category: "secondi",
    isWoodFired: false,
    isLocalSpecialty: false,
    allergens: ["glutine", "solfiti", "uova"],
  },
  {
    id: "secondi-11",
    name: "Cinghiale in Umido",
    description: "Braciola di cinghiale selvatico cotta a umido per ore nel forno a legna con vino rosso, funghi porcini, sedano, carota e aglio, servita con polenta morbida.",
    price: 16,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti", "sedano", "glutine"],
  },
  {
    id: "secondi-12",
    name: "Spiedini di Maiale alla Brace",
    description: "Cubetti di carne di maiale, peperoni arrostiti e cipolle caramellate, marinati in olio d'oliva, rosmarino e aglio, infilati su spiedini e cotti sulla brace del forno a legna.",
    price: 13,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: false,
    allergens: ["solfiti"],
  },
  {
    id: "secondi-13",
    name: "Ciscio di Pollo alla Diavola con Patate Arrosto",
    description: "Cosce di pollo intere cotte nel forno a legna con una glassa piccante di peperoncino, aglio e prezzemolo, accompagnate da patate arrosto croccanti con rosmarino.",
    price: 15,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: false,
    allergens: ["solfiti", "sedano"],
  },

    {
    id: "secondi-14",
    name: "Baccalà della Nonna",
    description: "Baccalà della nonna Rossella preparato con le prugne e il pomodoro, cotto nel forno a legna con patate novelle.",
    price: 18,
    category: "secondi",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti", "glutine"],
  },
  {
    id: "secondi-15",
    name: "Grigliata di Agnello",
    description: "Chops di agnello selvatico umbro, marinati con rosmarino e aglio, scottati sulla brace viva nel forno a legna.",
    price: 16,
    category: "secondi",
    isWoodFired: true,
    allergens: ["solfiti"],
  },
  {
    id: "secondi-16",
    name: "Parmigiana di Melanzane",
    description: "Melanzane locali grigliate nel forno a legna, cotte con sugo di pomodoro fresco, mozzarella di bufala e parmigiano Reggiano.",
    price: 10,
    category: "secondi",
    isWoodFired: true,
    isVegetarian: true,
    allergens: ["glutine", "latte"],
  },

  {
    id: "cont-1",
    name: "Verdure Grigliate",
    description: "Verdure stagionali della nostra terra, grigliate sul pezzo caliente del forno a legna con un filo di olio extravergine e una spolverata di sale.",
    price: 6,
    category: "contorni",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti"],
    isVegetarian: true,
  },
  {
    id: "cont-2",
    name: "Erba Cotta",
    description: "Verdure miste cotte in umido con olio extravergine e rosmarino, condite a fine cottura nel forno a legna.",
    price: 5,
    category: "contorni",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti"],
    isVegetarian: true,
  },
  {
    id: "cont-3",
    name: "Patate Arrosto",
    description: "Patate novelle arrosto nel forno a legna con rosmarino fresco e un filo di olio extravergine d\u2019oliva.",
    price: 5,
    category: "contorni",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti"],
    isVegetarian: true,
  },
  {
    id: "cont-4",
    name: "Patate sotto la Cenere",
    description: "Patate novelle cotte nel cenere del forno a legna, con la buccia croccante e la polpa morbida, condite con olio e rosmarino.",
    price: 5,
    category: "contorni",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti"],
    isVegetarian: true,
  },
  {
    id: "cont-5",
    name: "Broccoletti nel Coccio con Patate e Salsiccia",
    description: "Broccoletti freschi, patate novelle e salsiccia di maiale localmente rurdata, cotti insieme nel coccio di terracotta nel forno a legna.",
    price: 6,
    category: "contorni",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["solfiti"],
    isVegetarian: false,
  },
  {
    id: "cont-6",
    name: "Insalata di Finocchio e Arance",
    description: "Finocchi freschi e arance sanguinelle, conditi con olio extravergine d\u2019oliva, una spolverata di sale e una spolverata di finocchio selvatico.",
    price: 6,
    category: "contorni",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
    isVegetarian: true,
  },
  {
    id: "cont-7",
    name: "Insalata Mista",
    description: "Verdure fresche di stagione, rucola e pomodorini, conditi con olio extravergine d\u2019oliva e aceto balsamico.",
    price: 5,
    category: "contorni",
    allergens: ["solfiti"],
    isVegetarian: true,
  },
  {
    id: "cont-8",
    name: "Insalatona con Mozzarella di Bufala",
    description: "Rucola fresca, pomodorini rossi e gialli, cipolla rossa di Tropea e mozzarella di bufala D.O.P.",
    price: 10,
    category: "contorni",
    allergens: ["solfiti", "latte"],
    isVegetarian: true,
  },
  {
    id: "cont-9",
    name: "Insalatona con Tonno",
    description: "Rucola fresca, pomodorini, cipolla rossa di Tropea, olive nere e tonno sott\u2019olio, condito con olio extravergine d\u2019oliva e aceto balsamico.",
    price: 10,
    category: "contorni",
    allergens: ["solfiti", "pesce"],
    isVegetarian: false,
  },

{
    id: "dolci-1",
    name: "La Rocciata di Foligno",
    description: "Il celebre dolce medievale della nostra città. Una sfoglia sottilissima arrotolata a spirale e farcita con mele dell’Umbria, noci croccanti, pinoli, uvetta passita, cacao amaro, cannella e bagnata con alchermes prima della cottura a legna.",
    price: 6,
    category: "dolci",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "frutta a guscio", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "dolci-2",
    name: "Tiramisù Rustico al Vin Santo",
    description: "Tiramisù classico preparato in casa, ma con savoiardi bagnati nel Vin Santo artigianale umbro anziché nel liquore al caffè, e crema soffice al mascarpone.",
    price: 5.5,
    category: "dolci",
    isLocalSpecialty: true,
    allergens: ["glutine", "latte", "uova", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "dolci-3",
    name: "Tozzetti Artigianali con Vin Santo",
    description: "I tradizionali biscotti secchi umbri alle mandorle cotti nel forno a legna, serviti con un calice di Vin Santo DOC delle colline di Foligno per inzupparli.",
    price: 6.5,
    category: "dolci",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "frutta a guscio", "uova", "solfiti"],
    isVegetarian: true,
  },
    {
    id: "dolci-4",
    name: "Tiramis\u00f9 con Pavesini",
    description: "Tiramis\u00f9 classico con pavesini invece dei savoiardi, crema al mascarpone e una spolverata di cacao amaro.",
    price: 5,
    category: "dolci",
    allergens: ["glutine", "latte", "uova", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "dolci-5",
    name: "Panna Cotta",
    description: "Panna cotta avvolta da una glassa di caramello, cioccolato fondente o frutti di bosco, a vostra scelta.",
    price: 5,
    category: "dolci",
    allergens: ["latte", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "dolci-6",
    name: "Crema Catalana",
    description: "La classica crema spalmata con zucchero e cotta al forno fino a doratura, con una crosticina croccante e un cuore morbido.",
    price: 5,
    category: "dolci",
    isWoodFired: true,
    allergens: ["glutine", "latte", "uova"],
    isVegetarian: true,
  },
  {
    id: "dolci-7",
    name: "Crostata di Marmellata Fatta in Casa",
    description: "Crostata con la nostra marmellata artigianale fatta in casa con frutta di stagione, servita tiepida o a temperatura ambiente.",
    price: 5,
    category: "dolci",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "uova"],
    isVegetarian: true,
  },
  {
    id: "dolci-8",
    name: "Rocciata Dolce con Noci e Pinoli",
    description: "La nostra versione dolce della Rocciata di Foligno, con noci locali, pinoli e uva passata, arrotolata e cotta nel forno a legna con alchermes.",
    price: 5,
    category: "dolci",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "frutta a guscio", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "dolci-9",
    name: "Tozzetti con Mandorle e Sagrantino Passato",
    description: "Biscotti secchi alla mandorle fatti in casa, cotti nel forno a legna, serviti con un bicchierino di Sagrantino passato D.O.C.G.",
    price: 6,
    category: "dolci",
    isWoodFired: true,
    isLocalSpecialty: true,
    allergens: ["glutine", "frutta a guscio", "solfiti"],
    isVegetarian: true,
  },
  {
    id: "dolci-10",
    name: "Bicchierino di Sagrantino Passato D.O.C.G",
    description: "Un bicchiere di Sagrantino passato D.O.C.G, un dolce vino naturale umbro perfetto per accompagnare i nostri dessert.",
    price: 4,
    category: "dolci",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
    isVegetarian: true,
  },

// === Vini Rossi dell'Umbria - Sezione Cantina ===

  // Arnaldo-Caprai (Viticoltore Montefalco)
  {
    id: "vini-arc-1",
    name: "Montefalco Sagrantino DOCG - Arnaldo-Caprai (Collepiano)",
    description: "100% Sagrantino. Consigliato per carne arrostita, spezzatini e selvaggina.",
    price: 38,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-arc-2",
    name: "Pinot Nero IGT - Arnaldo-Caprai (Nero Outside)",
    description: "100% Pinot Nero. Consigliato per salumi, carne rossa e formaggi stagionati.",
    price: 32,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-arc-3",
    name: "Montefalco Rosso DOC - Arnaldo-Caprai",
    description: "70% Sangiovese, 15% Sagrantino, 15% Merlot. Consigliato per formaggi e arrosti.",
    price: 20,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-arc-4",
    name: "Montefalco Rosso Riserva DOC - Arnaldo-Caprai",
    description: "70% Sangiovese, 15% Sagrantino, 15% Merlot. Consigliato per formaggi e arrosti.",
    price: 28,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-arc-5",
    name: "Umbria Rosso IGT - Arnaldo-Caprai",
    description: "85% Sangiovese, 15% Canaiolo. Consigliato per pasta con sughi di carne.",
    price: 17,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },

  // Scacciadiavoli (di Pambuffetti)
  {
    id: "vini-sc-1",
    name: "Montefalco Sagrantino DOCG - Scacciadiavoli",
    description: "100% Sagrantino. Consigliato per arrosti, carni rosse alla brace e cacciagione.",
    price: 35,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-sc-2",
    name: "Montefalco Rosso DOC - Scacciadiavoli",
    description: "60% Sangiovese, 15% Sagrantino, 25% Merlot. Consigliato per primi piatti, carni bianche e rosse.",
    price: 20,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-sc-3",
    name: "Rosso dell'Umbria IGT - Scacciadiavoli",
    description: "Sangiovese - Merlot. Consigliato per antipasti e primi piatti saporiti.",
    price: 18,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },

  // Milziade Antano (Fattoria Colleallodole)
  {
    id: "vini-ma-1",
    name: "Montefalco Sagrantino DOCG - Milziade Antano",
    description: "100% Sagrantino. Consigliato per arrosti, carni rosse brasate o stufate.",
    price: 40,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-ma-2",
    name: "Montefalco Rosso DOC - Milziade Antano",
    description: "70% Sangiovese, 15% Sagrantino, 15% Merlot. Consigliato per primi piatti, carni bianche, rosse e formaggi.",
    price: 24,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },

  // Antonelli
  {
    id: "vini-an-1",
    name: "Montefalco Sagrantino DOCG - Antonelli",
    description: "100% Sagrantino. Consigliato per arrosti, carni rosse brasate o stufate.",
    price: 38,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-an-2",
    name: "Montefalco Sagrantino DOCG - Antonelli (0,375 Lt)",
    description: "100% Sagrantino. Consigliato per arrosti, carni rosse brasate o stufate.",
    price: 20,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-an-3",
    name: "Montefalco Rosso DOC - Antonelli",
    description: "70% Sangiovese, 15% Sagrantino, 15% Montepulciano. Consigliato per primi piatto, carni bianche e rosse.",
    price: 20,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-an-4",
    name: "Montefalco Rosso DOC - Antonelli (0,375 Lt)",
    description: "70% Sangiovese, 15% Sagrantino, 15% Montepulciano. Consigliato per primi piatto, carni bianche e rosse.",
    price: 12,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },

  // Di Filippo (vini da agricoltura biologica)
  {
    id: "vini-df-1",
    name: "Montefalco Sagrantino DOCG - Di Filippo",
    description: "100% Sagrantino, 18-24 mesi Barrique. Consigliato per arrosti, carni rosse alla brace e cacciagione.",
    price: 40,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-df-2",
    name: "Montefalco Sagrantino Etnico DOCG - Di Filippo",
    description: "100% Sagrantino, 12 mesi Legno. Consigliato per arrosti, carni rosse alla brace e cacciagione.",
    price: 32,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-df-3",
    name: "Montefalco Rosso DOC - Di Filippo",
    description: "60% Sangiovese, 30% Barbera, 10% Sagrantino Acciaio. Consigliato per carni rosse, salumi e formaggi.",
    price: 20,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-df-4",
    name: "Rosso dell'Umbria IGT (Terre San Nicola) - Di Filippo",
    description: "Sangiovese, Merlot, Sagrantino, 50% in tonneaux per 12 mesi. Consigliato per antipasti, primi carne e formaggi.",
    price: 22,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },

  // === Vini Rossi Extra-Regional ===

  // Toscana
  {
    id: "vini-tos-1",
    name: "Rosso di Montalcino DOC - Pian delle Vigne",
    description: "100% Sangiovese. Consigliato per salumi, carne rossa e formaggi stagionati.",
    price: 35,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-tos-2",
    name: "Il Bruciato Bolgheri DOC - Antinori",
    description: "65% Cabernet Sauvignon, 20% Merlot, 15% Syrah. Consigliato per carne arrostita.",
    price: 40,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-tos-3",
    name: "Pèppoli Chianti Classico DOCG",
    description: "90% Sangiovese, 10% Merlot e Syrah. Consigliato per salumi, carne rossa e formaggi stagionati.",
    price: 26,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-tos-4",
    name: "Le Difese Toscana IGT - Tenuta San Guido",
    description: "70% Cabernet, 30% Sangiovese. Consigliato per salumi, carne rossa o bianca e formaggi stagionati.",
    price: 40,
    category: "vini",
    allergens: ["solfiti"],
  },

  // Sardegna
  {
    id: "vini-sard-1",
    name: "Montessu IGT Isola dei Nuraghi - Agricola Punica",
    description: "60% autoctone, 40% Francesi. Consigliato per carne rossa e formaggi stagionati.",
    price: 30,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-sard-2",
    name: "Barrua - Agricola Punica",
    description: "85% autoctone, 15% Francesi. Consigliato per arrosti e carne alla brace.",
    price: 45,
    category: "vini",
    allergens: ["solfiti"],
  },

  // Veneto
  {
    id: "vini-ven-1",
    name: "Valpolicella DOC Classico Superiore - Speri",
    description: "70% Corvina Veronese, 20% Rondinella, 10% altri. Consigliato per carne e formaggi.",
    price: 30,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-ven-2",
    name: "Amarone della Valpolicella DOCG - Speri",
    description: "70% Corvone, 25% Rondinella, 5% Molinara. Consigliato per piatti robusti di carne.",
    price: 70,
    category: "vini",
    allergens: ["solfiti"],
  },

  // Friuli
  {
    id: "vini-fri-1",
    name: "Schioppettino Vini Orsone DOC - Bastianich",
    description: "100% Schioppettino. Vino molto versatile, consigliato per carne, formaggi e sughi.",
    price: 24,
    category: "vini",
    allergens: ["solfiti"],
  },

  // Piemonte
  {
    id: "vini-pie-1",
    name: "Occhetti Nebbiolo d'Alba DOC - Prunotto",
    description: "100% Nebbiolo. Consigliato per carne e formaggi.",
    price: 28,
    category: "vini",
    allergens: ["solfiti"],
  },

  // === Vini Bianchi ===
  // Umbria
  {
    id: "vini-bio-1",
    name: "Umbria Grechetto IGT Anima Umbra - Arnaldo Caprai",
    description: "85% Grechetto, 15% Trebbiano spoletino. Consigliato per antipasti, primi e carni bianche.",
    price: 17,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-2",
    name: "Montefalco Bianco DOC - Scacciadiavoli",
    description: "50% Grechetto, 25% Trebbiano spoletino, 25% Chardonnay. Consigliato per minestre, insalata di farro e piatti freschi.",
    price: 22,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-3",
    name: "Trebium Trebbiano Spoletino DOC - Antonelli",
    description: "100% Trebbiano spoletino. Consigliato per carni bianche e formaggi saporiti.",
    price: 22,
    category: "vini",
    isLocalSpecialty: true,
    isBiologico: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-4",
    name: "Grechetto (senza solfiti aggiunti) - Di Filippo",
    description: "100% Grechetto. Consigliato per carni bianche, formaggi e piatti strutturati.",
    price: 18,
    category: "vini",
    isLocalSpecialty: true,
    isBiologico: true,
    allergens: [],
  },
  {
    id: "vini-bio-5",
    name: "Cervaro della Sala - Umbria IGT",
    description: "Chardonnay, Grechetto. Consigliato per carni bianche e rosse e formaggi stagionati e aromatici.",
    price: 60,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-6",
    name: "Conte della Vipera - Umbria IGT",
    description: "Sauvignon Blanc, Sèmillon. Consigliato per carni bianche e formaggi stagionati e aromatici.",
    price: 40,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-7",
    name: "Bramito - Umbria IGT",
    description: "100% Chardonnay. Consigliato per minestre, insalata di farro e piatti freschi.",
    price: 30,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-8",
    name: "Orvieto DOC Classico Superiore - San Giovanni della Sala",
    description: "50% Grechetto, 25% Procanico, 25% Pinot Blanc e Viogner. Consigliato per minestre, insalata di farro e piatti freschi.",
    price: 30,
    category: "vini",
    allergens: ["solfiti"],
  },

  // === Vini Bianchi Extra-Regional ===
  {
    id: "vini-bio-9",
    name: "Marchese Antinori Cuvée Royale Franciacorta DOCG",
    description: "78% Chardonnay, 12% Pinot Nero, 10% Pinot Bianco. Consigliato per aperitivi e antipasti.",
    price: 38,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-10",
    name: "Deseo Prosecco DOC extra dry - Cantina Deseo",
    description: "100% Prosecco. Consigliato per aperitivo e antipasti.",
    price: 18,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-11",
    name: "'Stoass' Gewurztraminer - Pfitscher (Alto Adige DOC)",
    description: "100% Gewurztraminer. Consigliato per formaggi aromatici.",
    price: 28,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-bio-12",
    name: "Pinot Grigio DOC Colli Orientali - Bastianich",
    description: "100% Pinot Grigio. Consigliato per formaggi freschi e formaggi di media stagionatura.",
    price: 24,
    category: "vini",
    allergens: ["solfiti"],
  },

  // === Vini Bianchi/Rosati Extra-Regional ===
  // Caprai
  {
    id: "vini-extra-1",
    name: "Grecante dei Colli Martani DOC - Caprai",
    description: "100% Grechetto.",
    price: 22,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-extra-2",
    name: "Puntabella DOC Rosato dei Colli del Trasimeno - Caprai",
    description: "60% Sangiovese, 40% Grenache.",
    price: 23,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-extra-3",
    name: "Merlot - Caprai",
    description: "100% Merlot.",
    price: 40,
    category: "vini",
    allergens: ["solfiti"],
  },

  // Col Falco di Ruggeri
  {
    id: "vini-extra-4",
    name: "Umbria Rosso IGT - Col Falco di Ruggeri",
    description: "60% Sangiovese, 25% Merlot, 15% uve del territorio.",
    price: 18,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-extra-5",
    name: "Umbria Grechetto IGT - Col Falco di Ruggeri",
    description: "100% Grechetto.",
    price: 18,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-extra-6",
    name: "Umbria Chardonnay IGT - Col Falco di Ruggeri",
    description: "100% Chardonnay.",
    price: 20,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-extra-7",
    name: "Umbria Rosato IGT - Col Falco di Ruggeri",
    description: "50% Sangiovese, 50% uve del territorio.",
    price: 22,
    category: "vini",
    allergens: ["solfiti"],
  },

  // Tenuta Decugnano dei Barbi
  {
    id: "vini-extra-8",
    name: "Battito Umbria Rosso IGT - Tenuta Decugnano dei Barbi",
    description: "Cabernet Sauvignon, Sangiovese e Merlot.",
    price: 25,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-extra-9",
    name: "Ricordi d'Estate Umbria Bianco IGT - Tenuta Decugnano dei Barbi",
    description: "Cabernet Vermentino, Chardonnay e Sauvignon Blanc.",
    price: 20,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-extra-10",
    name: "Frammento Orvieto Classico DOC - Tenuta Decugnano dei Barbi",
    description: "Grechetto, Vermentino, Sauvignon Blanc e Procanico.",
    price: 23,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },

  // === Grandi Annate ===
  {
    id: "vini-grandi-1",
    name: "Montefalco Sagrantino DOCG - 25 anni",
    description: "100% Sagrantino, 24 mesi in Barrique.",
    price: 90,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-grandi-2",
    name: "Montefalco Sagrantino DOCG Collepiano - 22 mesi Barrique",
    description: "100% Sagrantino, 22 mesi in Barrique.",
    price: 55,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-grandi-3",
    name: "Montefalco Sagrantino - 18 mesi Barrique",
    description: "100% Sagrantino, 18 mesi in Barrique.",
    price: 50,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "vini-grandi-4",
    name: "Montefalco Sagrantino DOCG Passito",
    description: "100% Sagrantino, appassito circa due mesi.",
    price: 60,
    category: "vini",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },

  // === Super Tuscan ===
  {
    id: "vini-super-1",
    name: "Guidalberto",
    description: "60% Cabernet Sauvignon, 40% Merlot. Consigliato per carne rossa e formaggi stagionati.",
    price: 75,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-super-2",
    name: "Sassicaia - su prenotazione",
    description: "85% Cabernet Sauvignon, 15% Cabernet Franc. Consigliato per arrosti e carne alla brace.",
    price: 300,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-super-3",
    name: "Solaia - su prenotazione",
    description: "75% Cabernet Sauvignon, 5% Cabernet Franc, 20% Sangiovese. Consigliato per arrosti e carne alla brace.",
    price: 300,
    category: "vini",
    allergens: ["solfiti"],
  },
  {
    id: "vini-super-4",
    name: "Ornellaia Bolgheri Superiore 1997 - su prenotazione",
    description: "45% Cabernet Sauvignon, 38% Merlot, 10% Cabernet Franc, 7% Petit Verdot. Consigliato per carne rossa e formaggi stagionati.",
    price: 250,
    category: "vini",
    allergens: ["solfiti"],
  },

  // === Birre ===
  {
    id: "bevande-1",
    name: "Birra (Icnusa, Menabrea, Heineken, etc.)",
    description: "Selezione di birre italiane ed estere. Servizi disponibili su richiesta.",
    price: 5,
    category: "bevande",
    allergens: ["glutine", "solfiti"],
  },

  // === Bevande ===
  {
    id: "bevande-2",
    name: "Calice di Vino Bianco o Rosso",
    description: "Calice di vino della casa, bianco o rosso.",
    price: 6,
    category: "bevande",
    allergens: ["solfiti"],
  },
  {
    id: "bevande-3",
    name: "Calice di Vino Sagrantino 100%",
    description: "Calice di Montefalco Sagrantino DOCG puro, servito a temperatura corretta.",
    price: 7,
    category: "bevande",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "bevande-4",
    name: "Amaro",
    description: "Amaro umbro artigianale post-prandiale.",
    price: 4,
    category: "bevande",
    allergens: ["solfiti"],
  },
  {
    id: "bevande-5",
    name: "Grappa di Sagrantino D.O.C.G.",
    description: "Grappa distillata da mosto di Sagrantino DOCG, setaccata con legno di rovere.",
    price: 5,
    category: "bevande",
    isLocalSpecialty: true,
    allergens: ["solfiti"],
  },
  {
    id: "bevande-6",
    name: "Caffè",
    description: "Caffè espresso del mattino o decaffeinato.",
    price: 1.5,
    category: "bevande",
  },
  {
    id: "bevande-7",
    name: "Acqua (1Lt)",
    description: "Acqua naturale o frizzante.",
    price: 2.5,
    category: "bevande",
  },
  {
    id: "bevande-8",
    name: "Coperto",
    description: "Coperto di benvenuto, incluso in tutti i menù.",
    price: 2.5,
    category: "bevande",
  },
];

export const DAILY_SPECIALS: DailySpecial[] = [
  { id: "spec-anti-2", name: "I \"5 Cocci\" " },
  { id: "spec-primi-1", name: "Gnocchi al Sagrantino" },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'g-1',
    src: IMAGES.interior,
    alt: 'Interno accogliente della Trattoria del Corso con il maestoso forno a legna acceso',
    category: 'ambiente',
    title: 'La Nostra Trattoria'
  },
  {
    id: 'g-2',
    src: IMAGES.tagliere,
    alt: 'Gran tagliere misto di salumi e formaggi umbri artigianali',
    category: 'piatti',
    title: 'Il Gran Tagliere Umbro'
  },
  {
    id: 'g-3',
    src: IMAGES.rocciata,
    alt: 'La Rocciata di Foligno sfornata calda dal nostro forno a legna',
    category: 'piatti',
    title: 'La Tradizionale Rocciata'
  },
  {
    id: 'g-4',
    src: '/uploads/Gnocchi_Al_Sagrantino.jpg',
    alt: 'Gnocchi fatti in casa al Sagrantino, soffici e profumati',
    category: 'piatti',
    title: 'Gnocchi fatti in casa al Sagrantino'
  },
  {
    id: 'g-5',
    src: '/uploads/Pollo_Al_Coccio.jpg',
    alt: 'Pollo al coccio cotto nel forno a legna nei tipici tegami di terracotta',
    category: 'piatti',
    title: 'Pollo al Coccio'
  },
  {
    id: 'g-6',
    src: '/uploads/Forno_a_Legna.jpg',
    alt: 'La brace che arde nel nostro storico forno a legna in cucina',
    category: 'dettagli',
    title: 'La Brace Viva'
  },
  {
    id: 'g-7',
    src: '/uploads/Entrata.jpg',
    alt: 'La porta principale di ingresso della Trattoria del Corso',
    category: 'ambiente',
    title: 'Porta Principale'
  },
  {
    id: 'g-8',
    src: '/uploads/Esterno.jpg',
    alt: 'Il corridoio esterno della Trattoria del Corso',
    category: 'ambiente',
    title: 'Corridoio Esterno'
  }
];

export const REVIEWS: Review[] = [];

